Attempt to fix this stacktrace:
Unable to files(*[], **{}): files() takes exactly 3 non-keyword arguments (2 given)
Traceback (most recent call last):
  File "/opt/anki_server/src/anki-sync-server/AnkiServer/threading.py", line 95, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/opt/anki_server/src/anki-sync-server/AnkiServer/collection.py", line 58, in execute
    ret = func(*args, **kw)
  File "/opt/anki_server/src/anki-sync-server/AnkiServer/apps/sync_app.py", line 442, in runFunc
    result = func(**data)
TypeError: files() takes exactly 3 non-keyword arguments (2 given)

I don't know how this happens because I don't see anywhere in the Anki
2.0.11 or 2.0.12 code base where files() is called without one of it's
arguments - but this stacktrace comes from a live site!